### ISSUE TITLE
Выпадающее меню услуг

### ISSUE THREAD

**Issue by foxhable** [aaccent/med-tourism#5]
Нужно добавить:
- Тень
- Стилизованный скролл
- Перекрытие с градиентом "прозрачный-белый"
- Активное состояние на кнопку "Услуги"

<details><summary>Сравнение</summary>

![image](https://github.com/aaccent/med-tourism/assets/36298346/15ba928a-90a0-41c1-911e-c458c53fb4b6)
</details>

**Comment by RamizAshurov** [comment]
1. В макете в стилях тени не было, добавил свою
2. Обернул меню в swiper для полного контроля над скроллбаром
3. Добавил градиент
4. Повесил активное состояние на кнопку "Услуги"

**Comment by foxhable** [comment]
1. А точно, теней там нет, там разные цвета фонов. Убери тень и задний фон шапки должен быть `#FAFAFA`, а не `#ffffff`. Тоже самое с футером, он не чисто белый

2. Cвайпер лишнее и неотзывчиво, лучше сделать через css. От нас не требуется, чтобы во всех браузерах был одинаковый стиль скрола, достаточно в хромиум подобных.

```scss
.submenu {
  &__categories {
    scrollbar-color: #112233 hsla(210, 50%, 13%, 0.2);
  
    &::-webkit-scrollbar {
        width: 10px;
        background: transparent;
    }
  
    &::-webkit-scrollbar-track {
        border: 1px solid hsla(210, 50%, 13%, 0.2);
        border-radius: 6px;
        background: transparent;
    }
  
    &::-webkit-scrollbar-thumb {
        background: #112233;
        border-radius: 6px;
    }
  
    &::-webkit-scrollbar-button:vertical:increment {
        height: 40px;
    }
  }
}
```
